from django.urls import path
from Dashboard.views import *
from django.conf import settings
from django.conf.urls.static import static
urlpatterns=[
    path('photology.html',photology),
    path('a.html',a),
    path('a1.html',a1),
    path('a2.html',a2),
    path('a3.html',a3),
    path('a4.html',a4),
    path('a5.html',a5),
    path('a6.html',a6),
    path('a7.html',a7),
    path('a8.html',a8),
    path('a9.html',a9),
    path('a91.html',a91),
    # path('a92.html',a92),
    path('b.html',b),
    path('b1.html',b1),
    path('b2.html',b2),
    path('b3.html',b3),
    path('b4.html',b4),
    path('b5.html',b5),
    path('b6.html',b6),
    path('b7.html',b7),
    path('b8.html',b8),
    path('b9.html',b9),
    path('b10.html',b10),
    path('b11.html',b11),
    path('b12.html',b12),
    path('b13.html',b13),
    path('b14.html',b14),
    path('c.html',c),
    path('c1.html',c1),
    path('c2.html',c2),
    path('c3.html',c3),
    path('c4.html',c4),
    path('c5.html',c5),
    path('c6.html',c6),
    path('c7.html',c7),
    path('c8.html',c8),
    path('c9.html',c9),
    path('c10.html',c10),
    path('c11.html',c11),
    path('c12.html',c12),
    path('c13.html',c13),
    path('c14.html',c14),
    path('c15.html',c15),
    path('c16.html',c16),
    path('c17.html',c17),
    path('c21.html',c21),
    path('c22.html',c22),
    path('rsw.html',rsw),
    path('rpw.html',rpw),
    path('sy.html',sy),
    path('psfMTF.html',psfMTF),
    path('test.html',test),
    path('syrecord.html',syrecord),
    path('datav.html',datav),
]+ static(settings.STATIC_URL, document_root=settings.STATICFILES_DIRS[0])